# Generated by Django 4.0.5 on 2022-06-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogtype',
            name='type_name',
            field=models.CharField(help_text='请输入记事本的标题', max_length=20, verbose_name='标题'),
        ),
    ]
