# Generated by Django 4.0.5 on 2022-07-17 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0005_blogs_topic_delete_blog_delete_blogtype_blogs_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='added_date',
        ),
    ]
