# Generated by Django 4.0.5 on 2022-06-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='请输入记事标题', max_length=5, verbose_name='标题')),
                ('text', models.TextField(help_text='请输入记事内容', max_length=20, verbose_name='内容')),
                ('s_time', models.DateTimeField(help_text='请选择开始时间', verbose_name='开始时间')),
                ('e_time', models.DateTimeField(help_text='请选择结束时间', verbose_name='结束时间')),
                ('status', models.CharField(choices=[('U', 'Underway'), ('F', 'Finish'), ('D', 'Deleted')], default='U', help_text='请选择状态', max_length=1, verbose_name='状态')),
            ],
        ),
    ]
