# Generated by Django 4.0.5 on 2022-07-17 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call_num',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('sex', models.CharField(max_length=4)),
                ('phone', models.TextField(help_text='please input strs')),
            ],
        ),
    ]
